### ISSUE TITLE
Componente para cadastro e visualização de Estudantes

### ISSUE THREAD

**Issue by hectorhm** [olimpiada-paraibana-de-informatica/frontend#1]
**Requisitos**
* Delegado
1. Delegado envia informações dos Estudantes (Nome Completo, Data de Nascimento, Gênero)
2. Delegado recebe confirmação de cadastro de todos os Estudantes de sua Escola
2A. (ocorreu algum erro): uma mensagem de erro deve ser exibida e alguma tentativa de recuperação de erro indicada
* Administrador 
1. Administrador envia informações dos Estudantes (Nome Completo, Data de Nascimento, Gênero e Identificador da Escola)
2. Administrador recebe confirmação de cadastro de todos os Estudantes da Escola
2A. (ocorreu algum erro): uma mensagem de erro deve ser exibida e alguma tentativa de recuperação de erro indicada

**Tasks**
 * Delegado
- [x] Menu para cadastro de Estudantes (privilégio CA_ST - Create Associated School)
     * não faço ideia de como organizar esse menu, equipe do front deve sugerir uma maneira
- [x] Form (com validação de campos) para cadastro de Estudantes (privilégio CA_ST - Create Associated School)
- [x] Tela para visualização de Estudantes relacionados com sua Escola (privilégio IA_ST - Index Associated School)

 * Administrador
- [x] Menu para cadastro de Estudantes (privilégio C_ST - Show School)
     * não faço ideia de como organizar esse menu, nem se um menu é necessário, equipe do front deve sugerir uma maneira
- [x] Form (com validação de campos) para cadastro de Estudantes (privilégio C_ST - Create School)
- [x] Tela de Detalhes da Escola deve ter Lista de Estudantes associados (privilégio I_ST - Index School)

_**OBS.: Frontend deve escolher, por hora, a maneira mais simples e mais fácil de implementar essas funcionalidades. Pode-se, por exemplo, aproveitar a mesma estratégia e as mesmas telas para cada coisa, mudando apenas os detalhes de acordo com o privilégio em questão. Não é preciso seguir a task tal como está escrita.**_
