### ISSUE TITLE
Lista de Competidores deve aproveitar mais a tela, pois seus dados estão muito justos

### ISSUE THREAD

**Issue by erijonhson** [olimpiada-paraibana-de-informatica/frontend#24]
**Requisitos**
Visual limpo e importante. Ou aumenta a área para apreciação dos dados, ou diminui a quantidade de colunas na tabela, ou as duas coisas - é desconfortável numa tela de 14", então não estou certo se é necessário, de fato.

**Tasks**
- [ ] Aumentar área da tabela para melhor apreciação dos dados, se preciso
- [ ] Diminuir número de colunas, se preciso
   - [ ] nesse caso, será preciso fazer tela ou modal para detalhes de Escolas, para mostrar todos os dados
