### ISSUE TITLE
Delegado deve ter acesso apenas à Escola com ele relacionada

### ISSUE THREAD

**Issue by olimppb** [olimpiada-paraibana-de-informatica/frontend#5]
**Requisitos**
Haverá privilégios diferentes para observar todas as escolas ou apenas a escola relacionada com o Usuário do Token. Dessa forma, o backend fornecerá endpoint específico que permite observar todas as escolas (provavelmente /api/schools/), uma escola apenas (provavelmente /api/schools/{id}), ou observar escola a partir do token (provavelmente /api/schools/delegates/). 

**Tasks**
- [x] Menus para Usuário com privilégio I_SC (Index School), S_SC (Show School);
- [x] Menu para Usuário com privilégio SA_SC (Show Associated School);
- [x] Menu para Usuário com privilégio UA_SC (Update Associated School);
- [x] Esconder menus I_SC, S_SC quando Usuário não tiver essas permissões.
