### ISSUE TITLE
Implementar componente para Competidor

### ISSUE THREAD

**Issue by tharyck** [olimpiada-paraibana-de-informatica/frontend#6]
Após o cadastro do estudante, este deve ser cadastrado como competidor, dessa forma haverá um End-Point em que o delegado passa a lista dos Id's dos alunos da escola/instituição que ele faz parte, o ano que cada competidor cursa e enviar para o back, que ficará responsável por categorizar o grupo de cada aluno.

**Tasks**

- Menu para cadastrar competidores:

- [x] Menus para Usuário com privilégio IA_ST (Index Student);
- [x]  Menu para Usuário com privilégio C_CO (Create_Competitor);
- [x]  Menu para Usuário com privilégio U_CO (Update_Competitor);
- [x]  Menu para Usuário com privilégio D_CO (Delete_Competitor);
- [x]  Menu para Usuário com privilégio I_CO (Index_Competitor);
- [x]  Menu para Usuário com privilégio S_CO (Show_Competitor);

* Caso Ocorra sucesso no cadastro, uma mensagem deve ser exibida.
* Caso Ocorra Falha, uma mensagem deve ser exibida.
