### ISSUE TITLE
Cadastro de Escolas deve constar cidade e estado no frontend

### ISSUE THREAD

**Issue by olimppb** [olimpiada-paraibana-de-informatica/frontend#7]
**Requisitos**
Estudantes de qualquer cidade do país podem se matricular na OPI, não apenas da Paraíba.

**Tasks**
- [x] escolher Estado Brasileiro
- [x] mostrar lista das cidades do Estado escolhido e obrigar o usuário a escolher uma delas
- [x] enviar código cbo da cidade escolhida para cadastro da escola (vide swagger docs relacionados)
